spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kafka_FDS?useSSL=false&serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  kafka:
    template:
      default-topic: order


